
mycluster=parcluster('local');
mycluster.NumWorkers=7;
parpool(7);


lb = zeros(18*8,1);
ub = lb + 10;
options = optimoptions('ga',...
    'Display','iter',...
    'MaxGenerations', 10,...
    'UseParallel', true,...
    'PopulationSize', 50000,...
    'PlotFcns', 'gaplotbestf');
[x,fval,exitflag,output,population,scores]...
    = ga(@ga_arm_sim,18*8,[],[],[],[],lb,ub,[],options);

[~,out] = ga_arm_sim(x);